from pathlib import Path
from html import escape
D=Path('dist')
nav=[('Home','index.html'),('Research','research.html'),('People','personnel.html'),('Publications','publications.html'),('Videos','videos.html'),('News','news.html'),('Contact','contact.html')]
def page(title,file,body,desc):
 links=''.join(f'<a href="{url}"{(" aria-current=page" if url==file else "")}>{name}</a>' for name,url in nav)
 html=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(title)} | MER Lab · UNC Charlotte</title><meta name="description" content="{escape(desc)}"><link rel="stylesheet" href="style.css"><link rel="icon" type="image/svg+xml" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='13' fill='%230b5344'/%3E%3Cpath d='M10 44c13 0 13-24 26-24s13 24 18 24M36 20v-9M36 20l12-9M36 20l-12-9' fill='none' stroke='%23d3efad' stroke-width='5' stroke-linecap='round'/%3E%3C/svg%3E"></head><body><header class="mast"><div class="wrap mast-inner"><a class="brand" href="index.html" aria-label="MER Lab home"><span class="symbol" aria-hidden="true">⌁</span><span><b>MER Lab</b><small>UNC CHARLOTTE</small></span></a><button class="menu" aria-label="Toggle navigation" aria-expanded="false" aria-controls="main-nav">☰</button><nav class="nav" id="main-nav" aria-label="Main navigation">{links}</nav></div></header><main class="page">{body}</main><footer class="footer"><div class="wrap footer-inner"><span>© 2026 Microvascular Engineering &amp; Regeneration Laboratory · UNC Charlotte</span><a href="mailto:nzhao1@charlotte.edu">nzhao1@charlotte.edu</a></div></footer><script src="site.js" defer></script></body></html>'''
 (D/file).write_text(html)
def head(label,title,desc):return f'<section class="page-head"><div class="wrap"><div class="eyebrow">{label}</div><h1>{title}</h1><p>{desc}</p></div></section>'
page('Home','index.html','''<section class="hero"><div class="wrap hero-grid"><div><div class="eyebrow">Microvascular Engineering &amp; Regeneration Laboratory</div><h1>Human-specific microvascular models</h1><p>Our research is dedicated to engineering human-specific microvascular models to advance the understanding of microvessel regeneration, accelerate drug screening, and enable disease modeling.</p><p>By integrating stem cell technologies, biomaterials, and microfluidic platforms, we tackle these challenges across three core areas: developing human extracellular matrix (ECM) biomaterials, engineering functional microcirculation, and creating vascularized skin grafts.</p><div class="buttons"><a class="button" href="research.html">Explore research</a><a class="button outline" href="videos.html">Watch our work</a></div></div><div class="hero-visual"><img src="research.png" alt="Overview of the lab's human ECM, microcirculation, and vascularized skin projects"><span>Stem cells · Biomaterials · Microfluidics</span></div></div></section><section class="home-strip"><div class="wrap strip-grid"><div class="strip-item"><strong>Human ECM biomaterials</strong><span>Building better environments for human cells.</span></div><div class="strip-item"><strong>Functional microcirculation</strong><span>Engineering networks of arterioles, capillaries, and venules.</span></div><div class="strip-item"><strong>Vascularized skin grafts</strong><span>Bringing functional microvessels into engineered skin.</span></div></div></section><section class="home-bottom"><div class="wrap home-bottom-inner"><div><div class="eyebrow">From the lab</div><h2>See microvessels in motion</h2><p>Watch capillary growth and astrocyte endfeet in our video highlights.</p></div><a class="button" href="videos.html">View videos</a></div></section>''','Human-specific microvascular models, ECM biomaterials, and vascularized skin grafts at UNC Charlotte.')
research=head('Research','Building human-scale vascular systems','Our work combines stem cell technology, biomaterials, and microfluidics across three connected research directions.')+'''<section class="content"><div class="wrap"><div class="cards"><article class="card"><span class="index">01 / MATERIALS</span><h2>Engineering human ECM biomaterials</h2><p>Animal-derived matrices are common in tissue engineering, but differences between species can change how human cells behave. We aim to develop human ECM-like hydrogels using iPSC-derived cells, creating a more relevant foundation for engineered vessels.</p><div class="foot">Human cells · Hydrogels · Matrix biology</div></article><article class="card"><span class="index">02 / VESSELS</span><h2>Engineering functional microcirculation</h2><p>We build vessel models with the cells and supporting structures needed for long-term function, then connect arterioles, capillaries, and venules in a single network. The goal is to study flow, exchange, and vascular disease in systems that resemble human microcirculation.</p><div class="foot">Microfluidics · 3D templates · Flow</div></article><article class="card"><span class="index">03 / TISSUE</span><h2>Vascularized skin grafts</h2><p>Engineered skin often lacks functional microvessels, limiting how quickly it integrates after grafting. We are working to incorporate perfusable vessels into skin constructs to support survival and repair.</p><div class="foot">Engineered skin · Perfusion · Regeneration</div></article></div><figure class="diagram"><img src="research.png" alt="Diagram connecting the lab's ECM biomaterials, microcirculation, and skin graft research"><figcaption>Research overview from the MER Lab.</figcaption></figure></div></section>'''
page('Research','research.html',research,'Explore the MER Lab’s research in human ECM, functional microcirculation, and vascularized skin grafts.')
people=head('People','Meet the lab','An interdisciplinary team engineering human microvascular systems at UNC Charlotte.')+'''<section class="content"><div class="wrap"><div class="profile"><img src="nan-zhao.jpg" alt="Portrait of Dr. Nan Zhao"><div><h2>Dr. Nan Zhao</h2><p class="role">Principal Investigator · Assistant Professor</p><p>Dr. Zhao leads the Microvascular Engineering &amp; Regeneration Laboratory in the Department of Mechanical Engineering and Engineering Science. His research brings together human extracellular matrix biomaterials, tissue-engineered microvessels, and vascularized tissues.</p><p>His work includes models of brain angiogenesis and the blood–brain barrier, and he established the MER Lab at UNC Charlotte in 2025.</p><p><a href="mailto:nzhao1@charlotte.edu">Email Dr. Zhao</a> · <a href="https://cbes.charlotte.edu/people/nan-zhao/" target="_blank" rel="noopener">University profile ↗</a></p></div></div>
<section class="team-section" aria-labelledby="doctoral-team"><div class="eyebrow">Graduate research</div><h2 id="doctoral-team" class="section-title">Doctoral student</h2><div class="team-grid"><article class="member-card"><img src="zhen-qin.jpeg" alt="Zhen Qin" loading="lazy"><div class="member-info"><span class="member-level">PhD student</span><h3>Zhen Qin</h3><p class="program">First-year PhD student in Mechanical Engineering · Biomedical Engineering concentration</p><dl><dt>Research interests</dt><dd>Microvessel fabrication, mechanisms of angiogenesis, and basement membrane restoration</dd><dt>Fun fact</dt><dd>I made music during my undergraduate years.</dd></dl><a href="mailto:zqin4@charlotte.edu">zqin4@charlotte.edu</a></div></article></div></section>
<section class="team-section" aria-labelledby="masters-team"><div class="eyebrow">Graduate research</div><h2 id="masters-team" class="section-title">Master's students</h2><div class="team-grid"><article class="member-card"><img src="alex-howard.jpeg" alt="Alex Howard" loading="lazy"><div class="member-info"><span class="member-level">Master's student</span><h3>Alex Howard</h3><p class="program">Second-year M.S. student in Mechanical Engineering · Biomedical Engineering concentration</p><dl><dt>Project</dt><dd>Modeling blood–brain barrier dysfunction in Alzheimer’s disease using a tissue-engineered brain microvessel</dd><dt>Fun fact</dt><dd>I’ve run UNC Charlotte’s Smash Ultimate tournament series for the last three years.</dd></dl><a href="mailto:ahowar58@charlotte.edu">ahowar58@charlotte.edu</a></div></article>
<article class="member-card"><img class="ridthi-photo" src="ridthi-patel.jpeg" alt="Ridthi Patel" loading="lazy"><div class="member-info"><span class="member-level">Master's student</span><h3>Ridthi Patel</h3><p class="program">Second-year M.S. student in Cellular and Molecular Biology</p><dl><dt>Project</dt><dd>Keratinocyte differentiation and robust epidermis synthesis</dd><dt>Fun fact</dt><dd>I teach cardio dance at UREC.</dd></dl><a href="mailto:rpate250@charlotte.edu">rpate250@charlotte.edu</a></div></article>
<article class="member-card"><div class="photo-pending" role="img" aria-label="Allie Blab photo coming soon"><span>AB</span></div><div class="member-info"><span class="member-level">Master's student</span><h3>Allie Blab</h3><p class="program">Second-year M.S. student in Mechanical Engineering · Biomedical Engineering concentration</p><dl><dt>Project</dt><dd>Engineering human basement membrane-like biomaterials from induced pericytes</dd><dt>Fun fact</dt><dd>I am the VP of the Illustration Club on campus.</dd></dl></div></article></div></section>
<section class="team-section" aria-labelledby="undergraduate-team"><div class="eyebrow">Undergraduate research</div><h2 id="undergraduate-team" class="section-title">Undergraduate student</h2><div class="team-grid"><article class="member-card"><img class="deepu-photo" src="deepu-nallabothu.jpeg" alt="Deepu Shishir Nallabothu" loading="lazy"><div class="member-info"><span class="member-level">Undergraduate student</span><h3>Deepu Shishir Nallabothu</h3><p class="program">Second-year B.S. student in Biology · Chemistry minor</p><dl><dt>Research interest</dt><dd>Microvessel fabrication</dd><dt>Fun fact</dt><dd>I can solve a Rubik’s Cube in under a minute.</dd></dl><a href="mailto:dnallabo@charlotte.edu">dnallabo@charlotte.edu</a></div></article></div></section>
<div class="note"><strong>Interested in getting involved?</strong> For opportunities to work with the group, please <a href="mailto:nzhao1@charlotte.edu">contact Dr. Zhao</a>.</div></div></section>'''
page('People','personnel.html',people,'Meet Dr. Nan Zhao and the Microvascular Engineering & Regeneration Laboratory.')
pubs=[('2025','Brain vascular basement membrane: Comparison of human and mouse brain at the transcriptomic and proteomic levels','Matrix Biology'),('2024','Tissue-engineered microvessels: A review of current engineering strategies and applications','Advanced Healthcare Materials'),('2023','Modeling human brain angiogenesis with tissue-engineered venules','Angiogenesis'),('2022','Engineering the blood-brain barrier model at near-capillary scale with a double-templating technique','Advanced Functional Materials'),('2022','Dynamics of Borrelia Burgdorferi invasion and intravasation in a tissue engineered dermal microvessel model','Advanced Science')]
items=''.join(f'<article class="pub"><span class="year">{y}</span><div><h2>{t}</h2><p>{j}</p></div></article>' for y,t,j in pubs)
page('Publications','publications.html',head('Publications','Selected work','Publications spanning human vascular models, angiogenesis, biomaterials, and engineered tissues.')+f'<section class="content"><div class="wrap"><div class="pub-list">{items}</div><p style="margin-top:30px"><a class="plain-link" href="https://webpages.charlotte.edu/nzhao1/publications.html" target="_blank" rel="noopener">View the full publication list ↗</a></p></div></section>','Selected publications from the MER Lab and Dr. Nan Zhao.')
vid=head('Video highlights','Microvessels in motion','Watch examples of vascular growth and cell interactions captured by the lab.')+'''<section class="content"><div class="wrap video-grid"><article class="video-card"><video controls preload="metadata" playsinline aria-label="Capillary growth video"><source src="videos/capillarygrowth.mp4" type="video/mp4">Your browser does not support HTML video.</video><div class="video-text"><h2>Capillary growth</h2><p>Watch the development of a capillary network.</p></div></article><article class="video-card"><video controls preload="metadata" playsinline aria-label="Growth of astrocyte endfeet video"><source src="videos/ACendfeet.mp4" type="video/mp4">Your browser does not support HTML video.</video><div class="video-text"><h2>Growth of astrocyte endfeet</h2><p>Observe astrocyte endfeet growing around an engineered vessel.</p></div></article></div></section>'''
page('Videos','videos.html',vid,'Watch video highlights from the MER Lab, including capillary growth and astrocyte endfeet.')
news=head('News','Lab updates','Milestones and announcements from the Microvascular Engineering & Regeneration Laboratory.')+'''<section class="content"><div class="wrap"><article class="news-item"><time datetime="2025-08">August 2025</time><h2>The MER Lab is established at UNC Charlotte</h2><p>Dr. Nan Zhao launches the Microvascular Engineering &amp; Regeneration Laboratory in the Department of Mechanical Engineering and Engineering Science.</p></article></div></section>'''
page('News','news.html',news,'News and milestones from the MER Lab at UNC Charlotte.')
contact=head('Contact','Connect with the lab','Questions about our research or interested in collaboration? Get in touch with Dr. Zhao.')+'''<section class="content"><div class="wrap contact-grid"><div class="contact-card"><h2>Email</h2><p><a href="mailto:nzhao1@charlotte.edu">nzhao1@charlotte.edu</a></p><p style="margin-top:18px">For research inquiries and collaboration, email Dr. Zhao directly.</p></div><div class="contact-card"><h2>Visit</h2><p>Woodward Hall, Room 481C<br>UNC Charlotte<br>9201 University City Blvd<br>Charlotte, NC 28223</p><p style="margin-top:18px"><a href="https://maps.google.com/?q=Woodward+Hall+UNC+Charlotte" target="_blank" rel="noopener">Get directions ↗</a></p></div></div></section>'''
page('Contact','contact.html',contact,'Contact Dr. Nan Zhao and the MER Lab at UNC Charlotte.')
(D/'site.js').write_text("const b=document.querySelector('.menu'),n=document.querySelector('.nav');b.addEventListener('click',()=>{const open=n.classList.toggle('open');b.setAttribute('aria-expanded',String(open));b.textContent=open?'×':'☰'});n.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{n.classList.remove('open');b.setAttribute('aria-expanded','false');b.textContent='☰'}));")
